Repository Urban-Green-Lab/application, pull requests merged in 2020-10, with the labels that each got.

#22 updated readme with pg db setup
  .github/workflows/python-package.yml
  README.md
Labels: documentation

#44 Splash screen route and buttons
  browser/public/fixtures/activeEventQuizzesData.json
  browser/public/fixtures/leaderboardData.json
  browser/src/.eslintrc
  browser/src/components/App/index.js
  browser/src/components/Modal/index.js
  browser/src/components/views/Home.js
  browser/src/data/getActiveEvent.js
  browser/src/styles/components/_home.scss
  browser/src/styles/components/index.scss
  browser/src/styles/globals/_variables.scss
  browser/src/views/Home.js
  browser/src/views/Splash.js
Labels: frontend

#47 Countdown view
  browser/src/components/App/index.js
  browser/src/views/Countdown.js
  browser/src/views/Home.js
  browser/src/views/Splash.js
Labels: frontend

#60 Hh/csv download
  api/djangorestapp/admin.py
  api/djangorestapp/migrations/0009_auto_20201030_0343.py
  api/djangorestapp/models/quiz_taker.py
  api/djangorestapp/templates/base.html
  api/djangorestapp/templates/tutorial.html
Labels: Backend

#65 added leaderboard
  browser/src/components/App/index.js
  browser/src/data/getLeaderboardInfo.js
  browser/src/views/Leaderboard.js
Labels: frontend

#46 PR to master for updates to development
  README.md
  browser/public/_redirects
  browser/public/fixtures/activeEventQuizzesData.json
  browser/public/fixtures/leaderboardData.json
  browser/src/.eslintrc
  browser/src/components/Answers/index.js
  browser/src/components/App/index.js
  browser/src/components/Modal/index.js
  browser/src/components/Question/index.js
  browser/src/components/views/Home.js
  browser/src/data/getActiveEvent.js
  browser/src/data/getLeaderboardInfo.js
  browser/src/data/postUserObject.js
  browser/src/images/UglLogo.png
  browser/src/images/floatingBoxes.png
  browser/src/images/happyface.png
  browser/src/images/number1.png
  browser/src/images/number2.png
  browser/src/images/partypopper.png
  browser/src/images/question.png
  browser/src/images/sadface.png
  browser/src/images/sustaingame.png
  browser/src/styles/components/_app.scss
  browser/src/styles/components/_correctAnswers.scss
  browser/src/styles/components/_countdown.scss
  browser/src/styles/components/_home.scss
  browser/src/styles/components/_leaderboard.scss
  browser/src/styles/components/_modal.scss
  browser/src/styles/components/_quiz.scss
  browser/src/styles/components/_splash.scss
  browser/src/styles/components/index.scss
  browser/src/styles/components/initials.scss
  browser/src/styles/components/score.scss
  browser/src/styles/components/thanks.scss
  browser/src/styles/fonts/DomaineText-Bold.otf
  browser/src/styles/fonts/GT-Walsheim-Pro-Black.ttf
  browser/src/styles/globals/_fonts.scss
  browser/src/styles/globals/_variables.scss
  browser/src/styles/index.scss
  browser/src/views/Countdown.js
  browser/src/views/Home.js
  browser/src/views/Initials.js
  browser/src/views/Leaderboard.js
  browser/src/views/Quiz.js
  browser/src/views/Score.js
  browser/src/views/Splash.js
  browser/src/views/Thanks.js
Labels: frontend
